import json
import string
import random
from json import JSONDecodeError
from datetime import datetime, date

def Register(type,gamers_json_file,sellers_json_file,Email_ID,Username,Password,Contact_Number):
    '''Register Function || Already Given'''
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()
        return True
    elif type.lower()=='gamer':
        f=open(gamers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
            "Wishlist":[],
            "Cart":[],
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()

def Login(type,gamers_json_file,sellers_json_file,Username,Password):
    '''Login Functionality || Return True if successfully logged in else False || Already Given'''
    d=0
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
    else:
        f=open(gamers_json_file,'r+')
    try:
        content=json.load(f)
    except JSONDecodeError:
        return False
    for i in range(len(content)):
        if content[i]["Username"]==Username and content[i]["Password"]==Password:
            d=1
            break
    f.seek(0)
    f.truncate()
    json.dump(content,f)
    f.close()
    if d==0:
        return False
    return True

def AutoGenerate_ProductID():
    '''Return a autogenerated random product ID || Already Given'''
    product_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=4))
    return product_ID

def AutoGenerate_OrderID():
    '''Return a autogenerated random product ID || Already Given'''
    Order_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=3))
    return Order_ID

def days_between(d1, d2):
    '''Calculating the number of days between two dates || Already Given'''
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)

def Create_Product(owner,product_json_file,product_ID,product_title,product_type,price_per_day,total_stock_available):
    '''Creating a product || Return True if successfully created else False'''

    product ={
        "Seller Username": owner,
        "Product ID": product_ID,
        "Product Title": product_title,
        "Product Type": product_type,
        "Price Per Day": price_per_day,
        "Total Stock Available": total_stock_available
    }
    try:
        file = open(product_json_file, "r+")
        product1 = json.load(file)
        product1.append(product)
        file.seek(0)
        file.truncate()
        json.dump(product1, file)
    except JSONDecodeError:
        list1 = []
        list1.append(product)
        json.dump(list1, file)
    file.close()
    return True



    

def Fetch_all_Products_created_by_seller(owner,product_json_file):
    '''Get all products created by the seller(owner)'''
    file = open(product_json_file, "r+")
    products = []
    try:
        product1=json.load(file)
        for i in product1:
            if i["Seller Username"] == owner:
                products.append(i)
    except JSONDecodeError:
        pass
    return products


def Fetch_all_products(products_json_file):
    '''Get all products created till now || Helper Function || Already Given'''
    All_Products_list=[]
    file=open(products_json_file,'r')
    try:
        product1=json.load(file)
        All_Products_list=product1
    except JSONDecodeError:
        pass
    return All_Products_list

def Fetch_Product_By_ID(product_json_file,product_ID):
    '''Get product deatils by product ID'''
    file = open(product_json_file, "r+")
    products = []
    try:
        product1=json.load(file)
        for i in product1:
            if i["Product ID"] == product_ID:
                products.append(i)
    except JSONDecodeError:
        pass
    return products


def Update_Product(Username,product_json_file,product_ID,detail_to_be_updated,new_value):
    '''Updating Product || Return True if successfully updated else False'''

    file = open(product_json_file, "r+")
    product1 = json.load(file)
    for i in product1 :
        if i["Seller Username"]==Username and i["Product ID"] == product_ID:
            i[detail_to_be_updated] = new_value
            file.seek(0)
            file.truncate()
            json.dump(product1, file)
            return True
    file.close()
    return False


def Add_item_to_wishlist(Username,product_ID,gamers_json_file):
    '''Add Items to wishlist || Return True if added successfully else False'''
    file = open(gamers_json_file, "r+")
    product1 = json.load(file)
    for i in product1:
        if i["Username"] == Username:
            i["Wishlist"].append(product_ID)
            file.seek(0)
            file.truncate()
            json.dump(product1, file)
            return True
    file.close()
    return False


def Remove_item_from_wishlist(Username,product_ID,gamers_json_file):
    '''Remove items from wishlist || Return True if removed successfully else False'''
    file = open(gamers_json_file, "r+")
    product1 = json.load(file)
    for i in product1:
        if i["Username"] == Username:
            i["Wishlist"].remove(product_ID)
            file.seek(0)
            file.truncate()
            json.dump(product1, file)
            return True
    file.close()
    return False
    

def Add_item_to_cart(Username,product_ID,Quantity,gamers_json_file,booking_start_date,booking_end_date,products_json_file):
    '''Add item to the cart || Check whether the quantity mentioned is available || Return True if added successfully else False'''
    '''Add the Product ID, Quantity, Price, Booking Start Date, Booking End Date in the cart as list of dictionaries'''
    file = open (products_json_file, "r")
    product1 = json.load(file)
    price = 0
    for i in product1:
        if i["Product ID"] == product_ID and i["Total Stock Available"] >= Quantity:
            price = i["Price Per Day"]
            item_product = {
                "Product ID": product_ID,
                "Quantity": Quantity,
                "Price": price,
                "Booking Start Date": booking_start_date,
                "Booking End Date": booking_end_date
            }
            file1 = open(gamers_json_file, "r+")
            product2 = json.load(file1)
            for i in product2:
                if i["Username"] == Username:
                    i["Cart"].append(item_product)
                    file1.seek(0)
                    file1.truncate()
                    json.dump(product2, file1)
                    return True
            file1.close()
    file.close()
    return False

    

def Remove_item_from_cart(Username,product_ID,gamers_json_file):
    '''Remove items from the cart || Return True if removed successfully else False'''
    file = open(gamers_json_file, "r+")
    product1 = json.load(file)
    for i in product1:
        if i["Username"] == Username:
            cart = i["Cart"]
            for j in range(len(cart)):
                if cart[j]["Product ID"] == product_ID:
                    i["Cart"].pop(j)
                    file.seek(0)
                    file.truncate()
                    json.dump(product1, file)
                    return True
    file.close()
    return False
    

def View_Cart(Username,gamers_json_file):
    '''Return the current cart of the user'''

    cart = []
    file = open(gamers_json_file, 'r')
    try:
        product1 = json.load(file)
        for i in product1:
            if i["Username"] == Username:
                cart = i["Cart"]
    except JSONDecodeError:
        pass
    return cart

def Place_order(Username,gamers_json_file,Order_Id,orders_json_file,products_json_file):
    '''Place order || Return True is order placed successfully else False || Decrease the quantity of the product orderd if successfull'''
    file = open(gamers_json_file, "r")
    product1 = json.load(file)
    cart_product = []
    file.close()
    for i in product1:
        if i["Username"] == Username:
            if len(i["Cart"]) == 0:
                return False
            else:
                cart_product = i["Cart"]
    no_of_days = []
    qty = []
    price = []
    for i in cart_product:
        qty.append(i["Quantity"])
        price.append(i["Price"])
        start_date = i["Booking Start Date"].split("-")
        end_date = i["Booking End Date"].split("-")
        date_1 = date(int(start_date[0]),int(start_date[1]),int(start_date[2]))
        date_2 = date(int(end_date[0]), int(end_date[1]), int(end_date[2]))
        num = (date_2-date_1).days
        no_of_days.append(num)
        with open(products_json_file, "r") as file1:
            product2 = json.load(file1)
        for j in product2:
            if j["Seller Username"] == Username:
                if j["Product ID"] == i["Product ID"]:
                    j["Total Stock Available"] = j["Total Stock Available"] - i["Quantity"]
                    with open(products_json_file, 'w') as file3:
                        json.dump(product2, file3)

            return True
    return False


def View_User_Details(gamers_json_file,Username):
    '''Return a list with all gamer details based on the username || return an empty list if username not found'''
    file = open(gamers_json_file, "r+")
    products4 = []
    try:
        product1 = json.load(file)
        for i in product1:
            if i["Username"] == Username:
                products4.append(i)
    except JSONDecodeError:
        pass
    return products4
    

def Update_User(gamers_json_file,Username,detail_to_be_updated, updated_detail):
    '''Update the detail_to_be_updated of the user to updated_detail || Return True if successful else False'''
    with open(gamers_json_file, "r+") as file:
        product1 = json.load(file)

    for i in product1 :
        if i["Username"]==Username :
            i[detail_to_be_updated] = updated_detail
            with open(gamers_json_file, "w") as file1:
                json.dump(product1, file1)
            return True
    return False
    

def Fetch_all_orders(orders_json_file,Username):
        '''Fetch all previous orders for the user and return them as a list'''
        all_orders = []
    with open(orders_json_file, "r") as file:
        product1 = json.load(file)
    for i in product1:
        if i["Ordered by"] == Username:
            all_orders.append(i)
    return all_orders


